steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '-f'
      - Dockerfile
      - '-t'
      - >-
        ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${_VERSION}
      - '-t'
      - >-
        ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest
      - .
    dir: .
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '--all-tags'
      - >-
        ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}
images:
  - >-
    ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:${_VERSION}
  - >-
    ${_REGION}-docker.pkg.dev/${PROJECT_ID}/${_ARTIFACT_REGISTRY}/${_SERVICE_NAME}:latest
options:
  logging: CLOUD_LOGGING_ONLY
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
substitutions:
  _ARTIFACT_REGISTRY: outty-prod-repo
  _SERVICE_NAME: outty-backend
  _PROJECT_ID: outty-prod
  _REGION: us-east1
